### ISSUE TITLE
selection of next concept_id

### ISSUE THREAD

**Issue by BartSaelen** [OnroerendErfgoed/atramhasis#151]
Currently, when adding a new concept, the next concept_id is selected by getting the max concept_id for the conceptscheme and then adding 1. 
This is not thread safe and also has some business issues. When someone deletes the latest concept and then adds a new one, the new one will have the same id as the delete one.

We should think about the best way to solve this.
- keep the current query
- add a sequence for each conceptscheme
- use a global sequence

**Comment by koenedaele** [comment]
We need to take the interaction with #190 into account as well. If we go with a sequence, then the sequence needs to be updated as well.

**Comment by cahytinne** [comment]
* Is it possible to set a sequence for each conceptscheme?
* Is the sequence supported in sqlite? There is an auto increment option, but only on a primary key.

**Comment by koenedaele** [comment]
The current way of working might be a bit naieve, but it does work for most use cases. We can come back to this later.

**Comment by koenedaele** [comment]
@Wim-De-Clercq Can I get a technical analysis on this? How much of a risk do we run and how easy to fix is it?

**Comment by Wim-De-Clercq** [comment]
### > This is not thread safe and also has some business issues

This just needs a unique contraints across concept_id + conceptscheme_id. And in case of unique failures, the code should try again. ¹

### > When someone deletes the latest concept and then adds a new one, the new one will have the same id as the delete one.

That's indeed an issue right now that cannot just be solved with a unique constraint.

### > add a sequence for each conceptscheme

Custom sequences would be a possibility. But I don't think it's possible with sqlite (_officially_, we can insert into sqlite's sequence table ourselves but let's not).
Alternatively, keeping the current approach of seperate IDs per conceptscheme. We could just add a column to the conceptscheme table with the value of the current highest ID for that scheme.

It basically functions as a sequence, but it's in our own table. It's possibly slower than 'real' sequences. However it's not like this needs to support hundreds of inserts per second anyway.
Plus: sqlite actually uses a simple table as well.

> SQLite keeps track of the largest ROWID using an internal table named "sqlite_sequence". The sqlite_sequence table is created and initialized automatically whenever a normal table that contains an AUTOINCREMENT column is created. The content of the sqlite_sequence table can be modified using ordinary UPDATE, INSERT, and DELETE statements. But making modifications to this table will likely perturb the AUTOINCREMENT key generation algorithm. Make sure you know what you are doing before you undertake such changes.

We could insert into that table as well, and store our values there. But I think adding it to conceptscheme is clearer and keeps the solution less tied to sqlite.

Adding the column is easy. The current value is the current MAX value for the conceptscheme like the query does now.

Using the new column is also easy with the average database (SELECT FOR UPDATE on the conceptscheme table)... **But** sqlite doesn't support that.
When 2 simultaneous threads would update that same row. Sqlite should raise an error on commit though (instead of waiting for the lock like the average database). And when this happens, the code should retry ¹

### > use a global sequence

So that would basically be the ID of the column which has an AUTOINCREMENT in sqlite. I feel like it's weird to change the behaviour at this point. But it is possible and it is a good solution because noone really cares about the actual values of IDs. There is nothing wrong that the first concept in a new conceptscheme would start with ID 345 I think. 
Taking imports in account, we just have to check that the value of the sequence would be greater than the max ID of the imported concepts, if not -> update.

It would actually not be very easy to automatically have `concept_id` be equal to `id` in sqlite or to a different sequence due to sqlite's lack of sequence support.
We would need triggers, but you can't change the data before insert. So you'd need to first insert with a wrong concept_id, and then with an `AFTER_INSERT` trigger update it to what it should be.

The clean approach in my opinion would be to actually just line up the database Concept to the Skosprovider Concept model. 
In skosprovider a concept doesn't have both `id` and `concept_id`. 
So the database doesn't need that either:
```
<change PK to id + concept_scheme_id -- these are a lot of steps that I omitted.>

UPDATE concept
SET id = concept_id

ALTER TABLE  concept DROP COLUMN concept_id
```
And `(id, conceptscheme )` must be the PK.
In the code `id` just replaces `concept_id` everywhere. This is however:
- a change in skosprovider_sqlalchemy. Not atramhasis. 
- considering existing codebases exist, this is quite a backwards-incompatible change to make.


### My €0.02
The single sequence leaves us with the cleanest solution. Nothing tricky going on in the code where we must read and update sequences ourselves for every insert. The database can just use its own autoincrement sequence. Simple as that. **Except** when importing a new scheme, we should check the validity of the sequence. Not that new rows would be wrong even if we didn't update the sequence. But only to avoid `When someone deletes the latest concept and then adds a new one, the new one will have the same id as the delete one.`

The main downside are the 2 bullets i listed, it being a change in skosprovider_sqlalchemy, and it being not backwards-compatible friendly.

It has my preference but i can understand that the 2 bullets make you prefer our own "sequences" in the conceptscheme table.
----

¹ There is a chance we can just use https://docs.pylonsproject.org/projects/pyramid_tm/en/latest/#retries if that sqlite exception is retryable.
  If not, we'll have to make it so.

**Comment by koenedaele** [comment]
> So that would basically be the ID of the column which has an AUTOINCREMENT in sqlite. I feel like it's weird to change the behaviour at this point. But it is possible and it is a good solution because noone really cares about the actual values of IDs. There is nothing wrong that the first concept in a new conceptscheme would start with ID 345 I think.

I think you'd be surprised to see how many people get really upset about this, and concepts in a concept scheme nog being serial. Lots of people put meaning in things that shouldn't have meaning. We've also had kind of a feature request to have non-numeric id's in a conceptscheme, but currently we're not doing that.

I don't have an issue with changing things in skosprovider_sqlalchemy, that one mainly exists for Atramhasis anyway. I do think the BC break is rather large for fixin a fairly minor issue (judging by the fact we've never really had an issue).

The someone delete's a concept and so it's id gets reused is also fairly minor since it's only really a problem when the issue with the highest concept_id gets deleted after it's been in use for a long time. I can see the concept with the highest concept_id being deleted rather quickly after it was created (because it wasn't useful), but then it doesn't really matter that the id gets reused. 

All in all, right now I'm fine with adding the unique constraint on (conceptscheme_id + concept_id) and just retrying when creation fails. This doesn't fix the possibility of reusing an id, but I think that will be a minor issue after all.

If we do go the route of setting the concept_id to a global id, then that feels like a different release.
