### ISSUE TITLE
Unsupported languages during import

### ISSUE THREAD

**Issue by cedrikv** [OnroerendErfgoed/atramhasis#155]
What should be done with labels and notes in an unsupported language when importing a concept or collection?

**Comment by koenedaele** [comment]
Normally, when you post a Concept or Collection with languages that are unknown to Atramhasis, it will validate them and if they are valid according to the language-tags library, it will add them during the Concept add.

But I'm assuming this doesn't work for you because you are showing the Concept or Collection in a form to be edited BEFORE you send it to the service? And because the languages aren't in the dropdown that's a problem?

Although I think I've actually imported Concepts with unknown languages before and that seemed to work fine?

/cc @BartSaelen

**Comment by koenedaele** [comment]
Do we still need to do something here? @cedrikv ?

**Comment by cedrikv** [comment]
This is ok, there were issues because of hardcoded language lists in the javascript code

**Comment by cedrikv** [comment]
This issue happens again now that we made the labels and notes editable in the grid. The language is unknown to the app before the save.

**Comment by cedrikv** [comment]
Import works if you directly save the concept. If you want to edit the labels or notes first, the input field with the language wil lselect the default lang instead of the unknown one.
