### ISSUE TITLE
Update translation strings

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#180]
Check our translations with the 0.4.1 codebase. Document how updating these should actually work.

Figure out how translating larger text blocks like welcome.jinja2 works.

**Comment by koenedaele** [comment]
Could @cedrikv or @JDeVos have a look at the French translation? Preferably after #182 has been merged to master.

**Comment by BartSaelen** [comment]
we need a french translation for:
"matches"
"You can find more information about this project at"
"Our discussion forum"
"Our online documentation"
"Our issue tracker"
"type"
"language"
"change note"
"definition"
"editorial note"
"example"
"history note"
"scope note"
"note"
"Download as CSV"

and for the following text:
"Atramhasis is an open-source, web-based SKOS editor. You can use this webapplication to browse SKOS vocabularies, thesauri, authority files, word lists, ... through the public interface. Atramhasis also comes with an admin interface you can use to add, update and remove concepts to your vocabularies."

**Comment by BartSaelen** [comment]
should be adapted in atramhasis/locale/fr/LC_MESSAGES/atramhasis.po

**Comment by JDeVos** [comment]
Might need some context for:
"matches"
"changeNote"
"historyNote"
"scopeNote"
"note"
"authority files"

Don't think there is an actual term for:
"Issue tracker"

**Comment by BartSaelen** [comment]
those are SKOS specific terms, maybe we can leave them like that @koenedaele ?

**Comment by koenedaele** [comment]
All the SKOS ones can be left as they are. Could be that there's a french SKOS translation. I'll look that up for the next version.

@JDeVos What would you use for issue tracker in French? The same as in English or something similar, ie. "bug tracker"? Anyway, whatever sounds good to you is ok.

**Comment by JDeVos** [comment]
I found no acronym in French that matches SKOS. The full term exists (Système Simple d'Organisation de Connaissances) but it is always referred to the acronym SKOS. The W3C seems however to have an official doc for translating the SKOS Core Vocabulary to French. Maybe we could use that. http://www.w3.org/2004/02/skos/core/annotations/fr/2006-02-09.rdf

For issue tracker, I would use "Suivi des problèmes". It's the closest I can get to but its meaning is not as broad as issue tracker as it hints only at "problems", not improvements or changes, that's why it leaves me not quite satisfied.
I've seen other sites that use "Suivi des problèmes, des corrections et des améliorations" which is thorough but a bit lenghty.

**Comment by koenedaele** [comment]
Ok with "Suivi des problèmes", I think it's close enough.

I think that's the French translation I was referring to. I'll make a ticket for the next version to study it a bit and decide on what we want to use.
