### ISSUE TITLE
Requirements in scaffold

### ISSUE THREAD

**Issue by taeymma** [OnroerendErfgoed/atramhasis#344]
I feel there is something wrong here. When installing thesaurus => install req.txt from thesaurus to install atramhasis. Then you roll out atramhasis scaffold and overwrite this requirements file?? So you can't update for example atramhasis anymore, because in the atramhasis reqs there is no atramhasis..

**Comment by koenedaele** [comment]
Thesaurus 0.1.0 was written against Atramhasis 0.4.x
To update, you can do pip install -U Atramhasis. And then you can run pcreate atramhasis_demo --interactive (or whatever the cmd is) to update thesaurus. (Unless I'm missing something somewhere).

If we include atramhasis in the thesaurus req file, the update proc could be the same or could be: update the req file to the latest version of Atramhasis and run pip install -r requirements.txt. Running pcreate atramhasis_demo --interactive would overwrite our changes again. Doesn't seem like much of a difference.

I believe the real problem of not having atramhasis in the requirements.txt file is that if I try deploying thesaurus 0.1.0 right now, I will end up with an Atramhasis 0.5.0b3 in my virtualenv since the thesaurus setup.py includes Atramhasis but does not specify a version. And the thesaurus requirements file does noet specify an Atramhasis version.

So, I think we need to add the Atramhasis version of the atramhasis package at the time of running the pcreate command to the requirements.txt file? @BartSaelen ?

**Comment by taeymma** [comment]
I'm not using the demo scaffold for thesaurus. So this scaffold could be adapted to omit the req files?

Also, the atramhasis req is present in thesaurus, with the correct version number.

**Comment by koenedaele** [comment]
If you're not using a scaffold you're free to do as you please. Just need to be careful when updating.

General consenus is to restructure the requirements files into:
- atramhasis-requirements.txt
- requirements.txt (extends atramhasis-requirements.txt)
- atramhasis-requirements-dev.txt (extends requirements.txt)
- requirements-dev.txt (extends atramhasis-requirements-dev.txt)

When updating a scaffold, atramhasis-requirements.txt and atramhasis-requirements-dev.txt will be overwritten, the other two remain untouched. This way, when developing your instance you can add dependencies in requirements.txt/
