### ISSUE TITLE
Provide a docker file

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#415]
Would it be easy to provide a docker file for people who want to test Atramhasis?

**Comment by maarten-vermeyen** [comment]
If you want I can take a look at this. I'have some experience with deploying R shiny applications.

Do you want to distribute it on Docker Hub? If so, will you create a organisation and team and invite me? (mvermeyen).

**Comment by cedrikv** [comment]
@koenedaele What should I enter in these fields:
![image](https://user-images.githubusercontent.com/1849458/33187820-e7e5052a-d094-11e7-88e7-fbf4d7956405.png)

**Comment by koenedaele** [comment]
Hmm:

- Namespace: atramhasis
- Organization full name: atramhasis
- Company: Onroerend Erfgoed
- Location: Belgium
- Gravatar emal: Don't think we have one. Would be nive to have one attached to Atramahasis logo (the pointy thingy)
- Website url: atramhasis.readthedocs.io

**Comment by cedrikv** [comment]
Next stop:
![image](https://user-images.githubusercontent.com/1849458/33202408-b519a944-d0fc-11e7-8c65-916f2b3fb1e9.png)

**Comment by koenedaele** [comment]
What are we adding to docker? A demo instance to start with?

Repository name: demo
Short description: A simple demo of Atramhasis, a web-based SKOS editor for thesauri and other controlled vocabularies
Full description: I'll write something some other time.

**Comment by cedrikv** [comment]
Ok, created a repo: https://hub.docker.com/r/atramhasis/demo/
@maarten-vermeyen should be admin

**Comment by maarten-vermeyen** [comment]
OK, I'll get started. Would you like to mimick your production setup (Nginx + gunicorn) or just run waitress?

**Comment by maarten-vermeyen** [comment]
I've pushed a firs docker image which serves using waitress and exposes port 6543. You can forward the host port 6543 to the container's port with the following command.

```
sudo docker pull atramhasis/demo
sudo docker run -p 127.0.0.1:6543:6543 atramhasis/demo
```
The image inherits from the ubuntu base image. I won't tag it with the atramhasis version number yet, as we still may decide to use nginx and I might change it to use an unprivileged user.

@koenedaele Where should commit the dockerfile?

**Comment by koenedaele** [comment]
What do you suggest? The main Atramhasis repo sounds ok to me.

For a demo I’m fine with going with Waitress. Have you configured the cron jobs as well and included the ldf server?

**Comment by maarten-vermeyen** [comment]
No, at the moment, it's just the instructions from [demo instructions](http://atramhasis.readthedocs.io/en/latest/demo.html#running-a-demo-site.). I'll include the ldf-server. 

At the moment there is no persistence in the containers, so when the demo server is shut down all data is lost. Do we expect there to be long running demo containers? If so, how often does the cron have to run? Do you have an idea about how long the cron takes to run?

I could also make data persistent by mounting a host directory. This would make running the demo app less convenient though. Either the mount has to be preconfigured and a specified directoy would have to exist on the host (probably non-portable) or the user would have to customise the docker run command.

**Comment by maarten-vermeyen** [comment]
I've pushed a new image. Supervisor manages both services (slower startup). Both ports need to be specified for port forwarding.

```
sudo docker run -p 127.0.0.1:6543:6543 -p 127.0.0.1:3000:3000 atramhasis/demo
``` 
No cron jobs yet and I've had to create a seperate supervisor config file.

**Comment by koenedaele** [comment]
> At the moment there is no persistence in the containers, so when the demo server is shut down all data is lost. Do we expect there to be long running demo containers? If so, how often does the cron have to run? Do you have an idea about how long the cron takes to run?

I don't think persistence is important here. So, if I understand you correctly starting a docker container means that the whole installation including filling the database and dumping everything as rdf is run before the container is actually useable?

For the demo the cron jobs are not that important, the dump_rdf script just needs to run once, otherwise the downloads won't be there and the ldf server can't work.

**Comment by maarten-vermeyen** [comment]
The demo data and dumps are included in the image, but all changes made (through the interface or through cronjobs) will be lost when the container is shut down. This is useful for a demo environment, but bad for production use.

As it is now the demo image starts from the official ubuntu image and installs atramhasis from pip (thus reflecting the latest release). It runs pcreate to start of from a demo scaffold, populatess the demo database en runs the dumps. It also builds the ldf server from source and sets up the configuration in order to make it as easy as possible for somebody to start a demo container. It is in effect completely independent from the atramhasis git repo in the sense that it isn't cloned and only works with the results of pcreate from the pip release. It is basicly a zero config docker image so all the end user has to do is:

1. install docker
2. ``docker pull atramhasis/demo``
3. ``sudo docker run -p 127.0.0.1:6543:6543 -p 127.0.0.1:3000:3000 atramhasis/demo``
4. Open the browser on the host OS and visit localhost localhost:6543 (pyramid) or 3000(ldf)

For production use in docker it is recommended to split out the different services (database, pyramid, ldf-server), and run it in multiple containers which can be run with docker compose. I've have a mind to split it out anyway. This would remove the need to run supervisord and split of the build of the ldf_server, which takes quite a while and will probably(?) not need to change as often as our own builds.

I think we would like keep the demo seperated from a main dockerfile in the repository. The main dockerfile would be kept in the root of the repository and the main scaffold. The production docker file needs to be an image based on the config-files and source on the filesystem in order to reflect user changes and will probably need to be edited by the user in order to fit their choices and setup.

**Comment by maarten-vermeyen** [comment]
The workaround in #417 seems to work. Should we include it in the demo docker image (in effect stripping al authentication) until we can find a better authentication mechanism for the demo?

**Comment by koenedaele** [comment]
Yes, I'm going to create a version 0.6.3 that strips the authentication part from the demo site. Then you can use that version as the demo version.

**Comment by maarten-vermeyen** [comment]
OK, I've pushed to the new repository you've created and added a basic README. I'll rebuild, tag and push the image when you release 0.6.3. When the new image is available, I'll add the option of running a Docker image to the atramhasis documentation.

**Comment by koenedaele** [comment]
Version 0.6.4 has been released on Github, but not pypi. Should be there on Monday. Version 0.6.3 was not packaged the right way and even contained a few minor bugs that were fixed in 0.6.4.

I think you can still release to pypi yourself. I can't at the moment because my python environment is too old. @goessebr will release on Monday. If you want to release yourself, don't forget to execute python setup.py prepare before packaging as sdist and bdist_wheel

**Comment by maarten-vermeyen** [comment]
I've updated the docker image and created a 0.6.4 tag. It's pushed to docker hub.

**Comment by maarten-vermeyen** [comment]
I've created a pull request for the documentation (#435)

**Comment by 3kynox** [comment]
Sorry to reopen here, anyone wants to work on a atramhasis docker for a production use?
