### ISSUE TITLE
ZeroDivisionError while using the dump_rdf script on an empty thesaurus

### ISSUE THREAD

**Issue by goessebr** [OnroerendErfgoed/atramhasis#487]
I'm using the dump_rdf scipt to make rdf files of all of my thesauri. 1 of my thesauri is still empty waiting to get filled by the administrator.

 The script fails on this 1 empty thesaurus with following error message
```
Generating dump for GGA_MOTIVATIES
Number of triples in Graph: 4
Number of triples in Conceptscheme: 4
Traceback (most recent call last):
  File "/var/projects/thesaurus/venv/bin/dump_rdf", line 10, in <module>
    sys.exit(main())
  File "/var/projects/thesaurus/venv/local/lib/python2.7/site-packages/atramhasis/scripts/dump_rdf.py", line 101, in main
    avg_concept_triples = (triples - cs_triples) / (count_concepts + count_collections)
ZeroDivisionError: integer division or modulo by zero
```

**Comment by koenedaele** [comment]
This happens because the thesaurus only consists of conceptscheme info and has no concepts. I suggest we wrap the line that generates the avg # of concept triples in a try catch ZeroDivisionError and then set the avg to 0. Other options are checking that triples - cs_triples is > 0, but even then it's possible that count_concepts + count_collections is zero (but unlikely since that would mean there are no concepts or collections, but there are other subjects). So, I would just check for errors and set the result to 0.
