### ISSUE TITLE
Fix functional tests

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#488]

**Comment by Wim-De-Clercq** [comment]
I think the application in general needs to be fixed as well, not just the tests.

With updated libraries, the SQLAlchemyProviders doesn't want to register with a global registry anymore - As intended.

They will only work with request-scoped registries. To enable this, we need this in the settings:
```
skosprovider.skosregistry_location = request
```
Now, by default every request a new Registry is created. But it's empty. We'll need to **either**:
1. Add code which registers the providers to the registry for every request.
2. register a `skosprovider.skosregistry_factory` which creates a `Registry` and registers all providers.

In my opinion the 2nd option, with the factory, will be the best option. Because it will only execute this code when the registry is in fact accessed.
If, for example, the homepage is requested there may be no need for the registry to be created and all providers registered.

----
For tests, maybe it's best to immediately set it up the same as other applications within OE.

The functional test code currently executes a lot of code to set things up right. 
But we should be able to run an in-memory server with `webtest`
```python
app = main({}, **cls.settings)  # from atramhasis/__init__.py
testapp = TestApp(cls.app)
```
Once all changes are made, adding `skosprovider.skosregistry_location = request` to the test settings (to be created) should be enough.

**Comment by koenedaele** [comment]
Agreed that option 2 is the best way to go. It's also what was intended by pyramid_skosprovider.

**Comment by Wim-De-Clercq** [comment]
Additional required changes are:
- https://github.com/OnroerendErfgoed/skosprovider_getty/issues/59
Currently, GettyProvider can not work with skosprovider 0.7.0.

- We need an alembic upgrade for a new column for collections.
Because collections share the same table as concepts, this goes in the concept table as a nullable column.
```python
    op.add_column(
        'concept',
        sa.Column('infer_concept_relations', sa.Boolean(), nullable=True)
    )
```

**Comment by Wim-De-Clercq** [comment]
That line i mentioned is in the registry, yes.
https://github.com/koenedaele/skosprovider/blob/b923e1c32c7821d6be59c73a5849acb14c7b0c9b/skosprovider/registry.py#L98

**Comment by koenedaele** [comment]
Ok, will you send a PR to the skosprovider repo for the registry?
