### ISSUE TITLE
Add a link to view an entry after editing it in the Admin view

### ISSUE THREAD

**Issue by gaurav** [OnroerendErfgoed/atramhasis#791]
Steps taken:
1. Created a demo Atramhasis instance by following the instructions at https://atramhasis.readthedocs.io/en/latest/demo.html
2. Accessed the admin interface at http://0.0.0.0:6543/admin
3. Accessed the entry "oppida" and added an exact match from Getty Vocab.

Problem:
* I would now like to view the "oppida" entry (at http://0.0.0.0:6543/conceptschemes/HERITAGETYPE/c/1052) to confirm that my changed have been saved, but the only link to the oppida entry on this page uses the concept IRI for the entry (which is, correctly, https://id.erfgoed.net/thesauri/erfgoedtypes/1052), but this links to the erfgoed.net entry for oppida, not the one that I just edited on my local instance.

Expected:
* Adding a "View" button in addition to the "Merge", "Edit" and "Delete" button that went to this page would be great! Alternatively, the ID ("1052") could be a link to this page.

**Comment by koenedaele** [comment]
Interesting one. In our production environment this is not an issue because the IRI's point to that environment. Actually this demo data is an older copy of production data, so it should probably have its own IRI, but off course we can't provide a handler service for the demo that handles absolute IRI's. We could perhaps switch them to IRI's of the form http://localhost:6543/conceptschemes/HERITAGETYPES/c/1052#id. This would work as long as you deploy the demo with the default settings.

Providing a link to the local view page (eg. http://localhost:6543/conceptschemes/HERITAGETYPES/c/1052) and just leaving the IRI intact would indeed be easier and is probably sufficient for demo purposes.

**Comment by koenedaele** [comment]
Todo: add a view button the admin interface to view a concept in the public side.
