### ISSUE TITLE
Introduce new build tools

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#854]
We're still using setup.py while there are better options around.

**Comment by Wim-De-Clercq** [comment]
### Babel

There's a tight integration between babel and setuptools which only **just** got updated on their master branch. [commit](https://github.com/python-babel/babel/commit/bf7b2ca3dbb2953166e33d24c1dc800a4f7c97a8)
and it looks like we'll have to depend on setuptools because they don't. [Like here](https://github.com/mkdocs/mkdocs/blob/master/pyproject.toml#L52C1-L55C2)

Currently we can hide all the required options for pybabel in the setup.cfg file. There is no proper alternative in babel.
As see in the [mkdocs project](https://github.com/mkdocs/mkdocs/issues/2989) they replaced it by simply typing the full commands including all args.

There is a [long standing open issue](https://github.com/python-babel/babel/issues/777) for this in the babel project. This won't happen soon I guess.

I'm not exactly sure on what the steps are to build the wheels/sources for this project? 
We could probably write a build hook to automatically execute pybabel compile/extract/init/update actions before building the sources/wheel so they're always up-to-date and part of the distribution files.

**Comment by koenedaele** [comment]
I have very little knowledge of Babel, so I'm open to suggestion that make sense. Are we better off keeping the current setup around until Babel catches up?

**Comment by Wim-De-Clercq** [comment]
We don't have to. And even with my linked master commit not much would change (there would be no more setuptools dependency).

But in general some commands that we may have been used to are a little longer because `setup.cfg` is not automatically read.
```
old:
    $ python setup.py compile_catalog
new:
    $ pybabel compile --directory 'atramhasis/locale' --domain atramhasis --statistics true
```
(I'm updating it in `docs/source/development.rst`)

**Comment by Wim-De-Clercq** [comment]
Right now, atramhasis does not include font-awesome fonts due to manifest.in restrictions.
We have to make sure we these are added: `*ttf *svg *woff *woff2`
