### ISSUE TITLE
Unable to add a concept or edit a conceptscheme when there's only one provider

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#883]
Steps to reproduce:

- Install the empty scaffold
- Go to admin
- Two providers are present (AAT and TGN), and no editable conceptschemes
- Add a new provider
- It's impossible to select this conceptscheme because it's the only option.
- Add a second provider
- It's now possible to add concepts to both schemes because you can select the scheme
- Delete a provider
- It's no longer possible to edit a scheme or add concepts to it

**Comment by goessebr** [comment]
https://github.com/OnroerendErfgoed/atramhasis/blob/62612ef340475f110d907604bfadee3795df3f32/atramhasis/static/admin/src/app/ui/widgets/SearchPane.js#L167-L169

The activation of the buttons is triggered by an `onChange` event on the `conceptSchemeSelect` dropdown list.

- We could add a "Select scheme" option, allowing us to always trigger the event. In this case, the default "Select scheme" option should disable the buttons.
- We could simply enable the buttons at all times since a working instance will always have a scheme eventually.
- We could enable or disable the buttons on load. If concept schemes are present, the three buttons should be enabled. If no concept scheme is present, the buttons should be disabled.

Do you have a preference?

**Comment by koenedaele** [comment]
I was going to say that he third option woud not work if I just added a first scheme (since it would have been loaded without schemes), but I believe that a new scheme isn't automatically added to the list anyway, so a page refresh is needed always? Correct?

**Comment by goessebr** [comment]
Correct.

We also need to trigger a page reload or update the dropdown in the side menu after adding a provider or closing the provider addition pop-up for all options.

**Comment by koenedaele** [comment]
I'm fine either way, as long as it works. Go for what's easiest for frontend devs.

I assume we'll be doing a full UI update one day anyway, we can always review it then.
